apiVersion: v1
kind: Namespace
metadata:
  name: apache

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-2-4-17
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-2-4-17
  template:
    metadata:
      labels:
        app: apache-2-4-17
    spec:
      containers:
        - image: httpd:2.4.17
          imagePullPolicy: Always
          name: apache
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 180
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 180
           periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: apache-2-4-17
  namespace: apache
  labels:
    app: apache
spec:
  type: ClusterIP
  ports:
    - port: 82
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: apache-2-4-17
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-2-4-47
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-2-4-47
  template:
    metadata:
      labels:
        app: apache-2-4-47
    spec:
      containers:
        - image: httpd:2.4.47
          imagePullPolicy: Always
          name: apache
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 180
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 180
           periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: apache-2-4-47
  namespace: apache
  labels:
    app: apache
spec:
  type: ClusterIP
  ports:
    - port: 88
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: apache-2-4-47