apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-9-5
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1-9-5
  template:
    metadata:
      labels:
        app: nginx-1-9-5
    spec:
      containers:
        - image: nginx:1.9.5
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 3
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 3
           periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-9-5
  namespace: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 82
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-1-9-5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-17-4
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1-17-4
  template:
    metadata:
      labels:
        app: nginx-1-17-4
    spec:
      containers:
        - image: nginx:1.17.4-alpine-perl
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          livenessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 3
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 3
           periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-17-4
  namespace: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 86
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-1-17-4
